name: Compliance

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:

permissions:
  pull-requests: write

jobs:
  # Semantics for pr title e.g (feat: subject) commit style
  semantics:
    name: Semantics
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: amannn/action-semantic-pull-request@v5.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pr-compliance-checks:
    name: PR Compliance Checks
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: mtfoley/pr-compliance-action@v1.2.1
        with:
          body-auto-close: false
          protected-branch-auto-close: false
          watch-files: |
            package.json
            package-lock.json
          body-comment: >
            ## Issue Reference
            In order to be considered for merging, the pull request description must refer to a
            specific issue number. 
            This check is looking for a phrase similar to: "Fixes #XYZ" or "Resolves #XYZ" where XYZ is the issue
            number that this PR is meant to address.
          protected-branch-comment: >
            ## Protected Branch
            In order to be considered for merging, the pull request changes must
            not be implemented on the "%branch%" branch.
            
            In order to be considered for merging, the pull request title must match the specification's are given below. You can edit the title in order for this check to pass.
            
            Most often, our PR titles are something like one of these:
            - docs: correct typo in README
            - feat: implement dark mode"
            - fix: correct remove button behavior
            
            We would suggest that you close this PR and implement your changes as
            described above and open a new pull request.
  welcome:
    name: Welcome
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: semantics
    if: github.event.action == 'opened'
    steps:
      - uses: actions/first-interaction@v1.1.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |-
            Congrats on making your first Pull Request and thanks for taking the time to improve this project! ❤️! 🎉🍕
